name: Build and Deploy msp-fe

on:
   push:
      branches:
         - main

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

         - name: Build and push Docker image
           uses: docker/build-push-action@v4
           with:
              context: .
              file: Dockerfile
              push: true
              tags: phamtuankhoi/msp-fe:latest
              # build-args: |
              #    VITE_API_URL=${{ secrets.VITE_API_URL }}
              #    VITE_WS_DOMAIN=${{ secrets.VITE_WS_DOMAIN }}

         - name: Deploy to Droplet
           uses: appleboy/ssh-action@v0.1.10
           with:
              host: ${{ secrets.DROPLET_IP }}
              username: root
              password: ${{ secrets.DROPLET_PASSWORD }}
              script: |
                 docker rm -f msp-fe-container || true
                 docker rmi phamtuankhoi/msp-fe || true
                 docker-compose -f docker-compose.esg.yml pull msp-fe
                 docker-compose -f docker-compose.esg.yml up -d msp-fe
